name: Continous Build Multi (Branch Lint, Build, Test)

on:
    pull_request:
        paths-ignore:
            - "**.md"
            - "**.txt"
    workflow_dispatch:

jobs:
    build-lint-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup environment
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install package
              uses: pnpm/action-setup@v3
              with:
                  version: 9
            - run: pnpm install --frozen-lockfile
            - run: pnpm lint
            - run: pnpm test
            - run: pnpm build
