# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Create release and publish npm package

on:
    push:
        tags:
            - v*

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup environment
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 9

            - run: pnpm install --frozen-lockfile
            - run: pnpm lint
            - run: pnpm test
            - run: pnpm build

    publish-npm:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup environment
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: https://registry.npmjs.org/
                  scope: "@quatico"
            - name: Install package
              uses: pnpm/action-setup@v3
              with:
                  version: 9
            - run: pnpm install --frozen-lockfile

            - name: Extract release notes
              id: extract-release-notes
              uses: ffurrer2/extract-release-notes@v2
              with:
                  changelog_file: Release-Notes.md

            - name: Create release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  body: ${{ steps.extract-release-notes.outputs.release_notes }}
              env:
                  # The workflow permissions of the project must be updated to 'Workflows have read and write permissions in the repository for all scopes'
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish to npm
              run: pnpm publish-npm
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
